UPDATE public."Corrida" SET "Deleted"=NOW() WHERE "IsDeleted"=true;
UPDATE public."CorVeiculo" SET "Deleted"=NOW() WHERE "IsDeleted"=true;
UPDATE public."Endereco" SET "Deleted"=NOW() WHERE "IsDeleted"=true;
UPDATE public."FaixaDesconto" SET "Deleted"=NOW() WHERE "IsDeleted"=true;
UPDATE public."FaixaDescontoTaxista" SET "Deleted"=NOW() WHERE "IsDeleted"=true;
UPDATE public."Favorito" SET "Deleted"=NOW() WHERE "IsDeleted"=true;
UPDATE public."FormaPagamento" SET "Deleted"=NOW() WHERE "IsDeleted"=true;
UPDATE public."FormaPagamentoTaxista" SET "Deleted"=NOW() WHERE "IsDeleted"=true;
UPDATE public."Foto" SET "Deleted"=NOW() WHERE "IsDeleted"=true;
UPDATE public."GrupoUsuario" SET "Deleted"=NOW() WHERE "IsDeleted"=true;
UPDATE public."Localizacao" SET "Deleted"=NOW() WHERE "IsDeleted"=true;
UPDATE public."Passageiro" SET "Deleted"=NOW() WHERE "IsDeleted"=true;
UPDATE public."PontoTaxi" SET "Deleted"=NOW() WHERE "IsDeleted"=true;
UPDATE public."Rota" SET "Deleted"=NOW() WHERE "IsDeleted"=true;
UPDATE public."SolicitacaoCorrida" SET "Deleted"=NOW() WHERE "IsDeleted"=true;
UPDATE public."Tarifa" SET "Deleted"=NOW() WHERE "IsDeleted"=true;
UPDATE public."Taxista" SET "Deleted"=NOW() WHERE "IsDeleted"=true;
UPDATE public."UsuarioGrupoUsuario" SET "Deleted"=NOW() WHERE "IsDeleted"=true;
UPDATE public."Veiculo" SET "Deleted"=NOW() WHERE "IsDeleted"=true;
UPDATE public."VeiculoTaxista" SET "Deleted"=NOW() WHERE "IsDeleted"=true;

UPDATE public."Corrida" SET "Inserted"=NOW(), "Updated"=NOW() WHERE "IsDeleted"=false;
UPDATE public."CorVeiculo" SET "Inserted"=NOW(), "Updated"=NOW() WHERE "IsDeleted"=false;
UPDATE public."Endereco" SET "Inserted"=NOW(), "Updated"=NOW() WHERE "IsDeleted"=false;
UPDATE public."FaixaDesconto" SET "Inserted"=NOW(), "Updated"=NOW() WHERE "IsDeleted"=false;
UPDATE public."FaixaDescontoTaxista" SET "Inserted"=NOW(), "Updated"=NOW() WHERE "IsDeleted"=false;
UPDATE public."Favorito" SET "Inserted"=NOW(), "Updated"=NOW() WHERE "IsDeleted"=false;
UPDATE public."FormaPagamento" SET "Inserted"=NOW(), "Updated"=NOW() WHERE "IsDeleted"=false;
UPDATE public."FormaPagamentoTaxista" SET "Inserted"=NOW(), "Updated"=NOW() WHERE "IsDeleted"=false;
UPDATE public."Foto" SET "Inserted"=NOW(), "Updated"=NOW() WHERE "IsDeleted"=false;
UPDATE public."GrupoUsuario" SET "Inserted"=NOW(), "Updated"=NOW() WHERE "IsDeleted"=false;
UPDATE public."Localizacao" SET "Inserted"=NOW(), "Updated"=NOW() WHERE "IsDeleted"=false;
UPDATE public."Passageiro" SET "Inserted"=NOW(), "Updated"=NOW() WHERE "IsDeleted"=false;
UPDATE public."PontoTaxi" SET "Inserted"=NOW(), "Updated"=NOW() WHERE "IsDeleted"=false;
UPDATE public."Rota" SET "Inserted"=NOW(), "Updated"=NOW() WHERE "IsDeleted"=false;
UPDATE public."SolicitacaoCorrida" SET "Inserted"=NOW(), "Updated"=NOW() WHERE "IsDeleted"=false;
UPDATE public."Tarifa" SET "Inserted"=NOW(), "Updated"=NOW() WHERE "IsDeleted"=false;
UPDATE public."Taxista" SET "Inserted"=NOW(), "Updated"=NOW() WHERE "IsDeleted"=false;
UPDATE public."UsuarioGrupoUsuario" SET "Inserted"=NOW(), "Updated"=NOW() WHERE "IsDeleted"=false;
UPDATE public."Veiculo" SET "Inserted"=NOW(), "Updated"=NOW() WHERE "IsDeleted"=false;
UPDATE public."VeiculoTaxista" SET "Inserted"=NOW(), "Updated"=NOW() WHERE "IsDeleted"=false;
